/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CompileController;
import javax.swing.JPanel;

/**
 *
 * @author lucas
 */
public class CompileView extends javax.swing.JFrame {
    public static CompileView compileView;
    
    private final CompileController compileController = CompileController.getCompileController();

    /**
     * Creates new form CompileView
     */
    public CompileView() {
        initComponents();
    }
    
    public static CompileView getCompileView() {
        if (compileView == null) {
            compileView = new CompileView();
        }
 
        return compileView;
    }
    
    public void screen() {
        showNumberedBorder();
        compileController.inputMapKeys();
        
        configView();
    }
    
    private void configView() {
        jToolBar.setFloatable(false);
    }
    
    private void showNumberedBorder() {
        jEditor.setBorder(new NumberedBorder());
    }

    public JPanel getjMain() {
        return jMain;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMain = new javax.swing.JPanel();
        jToolBar = new javax.swing.JToolBar();
        jToolNewFile = new javax.swing.JPanel();
        jLabelMenu = new javax.swing.JLabel();
        jImageMenu = new javax.swing.JLabel();
        jToolOpenFile = new javax.swing.JPanel();
        jLabelMenu1 = new javax.swing.JLabel();
        jImageMenu1 = new javax.swing.JLabel();
        jToolSaveFile = new javax.swing.JPanel();
        jLabelMenu3 = new javax.swing.JLabel();
        jImageMenu3 = new javax.swing.JLabel();
        jToolCopy = new javax.swing.JPanel();
        jLabelMenu10 = new javax.swing.JLabel();
        jImageMenu10 = new javax.swing.JLabel();
        jToolPaste = new javax.swing.JPanel();
        jLabelMenu11 = new javax.swing.JLabel();
        jImageMenu11 = new javax.swing.JLabel();
        jToolCut = new javax.swing.JPanel();
        jLabelMenu12 = new javax.swing.JLabel();
        jImageMenu12 = new javax.swing.JLabel();
        jToolCompile = new javax.swing.JPanel();
        jLabelMenu13 = new javax.swing.JLabel();
        jImageMenu13 = new javax.swing.JLabel();
        jToolTeam = new javax.swing.JPanel();
        jLabelMenu14 = new javax.swing.JLabel();
        jImageMenu14 = new javax.swing.JLabel();
        jScrollPaneEditor = new javax.swing.JScrollPane();
        jEditor = new javax.swing.JTextArea();
        jDivider = new javax.swing.JSplitPane(javax.swing.JSplitPane.VERTICAL_SPLIT, jEditor, jMessages);
        jScrollPaneMessages = new javax.swing.JScrollPane();
        jMessages = new javax.swing.JTextArea();
        jStatusBar = new javax.swing.JPanel();
        jFilePath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 800));
        setResizable(false);

        jToolBar.setBorderPainted(false);
        jToolBar.setMargin(new java.awt.Insets(0, 0, 5, 0));
        jToolBar.setPreferredSize(new java.awt.Dimension(1500, 70));

        jToolNewFile.setBackground(new java.awt.Color(255, 255, 255));
        jToolNewFile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolNewFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToolNewFile.setPreferredSize(new java.awt.Dimension(120, 60));
        jToolNewFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToolNewFileMouseClicked(evt);
            }
        });

        jLabelMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu.setText("novo [ctrl-n]");

        jImageMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImageMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/new-file.png"))); // NOI18N

        javax.swing.GroupLayout jToolNewFileLayout = new javax.swing.GroupLayout(jToolNewFile);
        jToolNewFile.setLayout(jToolNewFileLayout);
        jToolNewFileLayout.setHorizontalGroup(
            jToolNewFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
            .addComponent(jImageMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jToolNewFileLayout.setVerticalGroup(
            jToolNewFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jToolNewFileLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jImageMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabelMenu)
                .addContainerGap())
        );

        jToolBar.add(jToolNewFile);

        jToolOpenFile.setBackground(new java.awt.Color(255, 255, 255));
        jToolOpenFile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolOpenFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToolOpenFile.setPreferredSize(new java.awt.Dimension(120, 60));
        jToolOpenFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToolOpenFileMouseClicked(evt);
            }
        });

        jLabelMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu1.setText("abrir [ctrl-o]");

        jImageMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImageMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/open-file.png"))); // NOI18N

        javax.swing.GroupLayout jToolOpenFileLayout = new javax.swing.GroupLayout(jToolOpenFile);
        jToolOpenFile.setLayout(jToolOpenFileLayout);
        jToolOpenFileLayout.setHorizontalGroup(
            jToolOpenFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMenu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
            .addComponent(jImageMenu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jToolOpenFileLayout.setVerticalGroup(
            jToolOpenFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jToolOpenFileLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jImageMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabelMenu1)
                .addContainerGap())
        );

        jToolBar.add(jToolOpenFile);

        jToolSaveFile.setBackground(new java.awt.Color(255, 255, 255));
        jToolSaveFile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolSaveFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToolSaveFile.setPreferredSize(new java.awt.Dimension(120, 60));
        jToolSaveFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToolSaveFileMouseClicked(evt);
            }
        });

        jLabelMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu3.setText("salvar [ctrl-s]");

        jImageMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImageMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/save.png"))); // NOI18N

        javax.swing.GroupLayout jToolSaveFileLayout = new javax.swing.GroupLayout(jToolSaveFile);
        jToolSaveFile.setLayout(jToolSaveFileLayout);
        jToolSaveFileLayout.setHorizontalGroup(
            jToolSaveFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMenu3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
            .addComponent(jImageMenu3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jToolSaveFileLayout.setVerticalGroup(
            jToolSaveFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jToolSaveFileLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jImageMenu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabelMenu3)
                .addContainerGap())
        );

        jToolBar.add(jToolSaveFile);

        jToolCopy.setBackground(new java.awt.Color(255, 255, 255));
        jToolCopy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolCopy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToolCopy.setPreferredSize(new java.awt.Dimension(120, 60));
        jToolCopy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToolCopyMouseClicked(evt);
            }
        });

        jLabelMenu10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenu10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu10.setText("copiar [ctrl-c]");

        jImageMenu10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImageMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/copy.png"))); // NOI18N

        javax.swing.GroupLayout jToolCopyLayout = new javax.swing.GroupLayout(jToolCopy);
        jToolCopy.setLayout(jToolCopyLayout);
        jToolCopyLayout.setHorizontalGroup(
            jToolCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMenu10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
            .addComponent(jImageMenu10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jToolCopyLayout.setVerticalGroup(
            jToolCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jToolCopyLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jImageMenu10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabelMenu10)
                .addContainerGap())
        );

        jToolBar.add(jToolCopy);

        jToolPaste.setBackground(new java.awt.Color(255, 255, 255));
        jToolPaste.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolPaste.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToolPaste.setPreferredSize(new java.awt.Dimension(120, 60));
        jToolPaste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToolPasteMouseClicked(evt);
            }
        });

        jLabelMenu11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenu11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu11.setText("colar [ctrl-v]");

        jImageMenu11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImageMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/paste.png"))); // NOI18N

        javax.swing.GroupLayout jToolPasteLayout = new javax.swing.GroupLayout(jToolPaste);
        jToolPaste.setLayout(jToolPasteLayout);
        jToolPasteLayout.setHorizontalGroup(
            jToolPasteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMenu11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
            .addComponent(jImageMenu11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jToolPasteLayout.setVerticalGroup(
            jToolPasteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jToolPasteLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jImageMenu11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabelMenu11)
                .addContainerGap())
        );

        jToolBar.add(jToolPaste);

        jToolCut.setBackground(new java.awt.Color(255, 255, 255));
        jToolCut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolCut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToolCut.setPreferredSize(new java.awt.Dimension(120, 60));
        jToolCut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToolCutMouseClicked(evt);
            }
        });

        jLabelMenu12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenu12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu12.setText("recortar [ctrl-x]");

        jImageMenu12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImageMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cut.png"))); // NOI18N

        javax.swing.GroupLayout jToolCutLayout = new javax.swing.GroupLayout(jToolCut);
        jToolCut.setLayout(jToolCutLayout);
        jToolCutLayout.setHorizontalGroup(
            jToolCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMenu12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
            .addComponent(jImageMenu12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jToolCutLayout.setVerticalGroup(
            jToolCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jToolCutLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jImageMenu12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabelMenu12)
                .addContainerGap())
        );

        jToolBar.add(jToolCut);

        jToolCompile.setBackground(new java.awt.Color(255, 255, 255));
        jToolCompile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolCompile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToolCompile.setPreferredSize(new java.awt.Dimension(120, 60));
        jToolCompile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToolCompileMouseClicked(evt);
            }
        });

        jLabelMenu13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenu13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu13.setText("compilar [F7]");

        jImageMenu13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImageMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/compile.png"))); // NOI18N

        javax.swing.GroupLayout jToolCompileLayout = new javax.swing.GroupLayout(jToolCompile);
        jToolCompile.setLayout(jToolCompileLayout);
        jToolCompileLayout.setHorizontalGroup(
            jToolCompileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMenu13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
            .addComponent(jImageMenu13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jToolCompileLayout.setVerticalGroup(
            jToolCompileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jToolCompileLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jImageMenu13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabelMenu13)
                .addContainerGap())
        );

        jToolBar.add(jToolCompile);

        jToolTeam.setBackground(new java.awt.Color(255, 255, 255));
        jToolTeam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolTeam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToolTeam.setPreferredSize(new java.awt.Dimension(120, 60));
        jToolTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToolTeamMouseClicked(evt);
            }
        });

        jLabelMenu14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenu14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu14.setText("equipe [F1]");

        jImageMenu14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImageMenu14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/team.png"))); // NOI18N

        javax.swing.GroupLayout jToolTeamLayout = new javax.swing.GroupLayout(jToolTeam);
        jToolTeam.setLayout(jToolTeamLayout);
        jToolTeamLayout.setHorizontalGroup(
            jToolTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMenu14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
            .addComponent(jImageMenu14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jToolTeamLayout.setVerticalGroup(
            jToolTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jToolTeamLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jImageMenu14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabelMenu14)
                .addContainerGap())
        );

        jToolBar.add(jToolTeam);

        jScrollPaneEditor.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPaneEditor.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jEditor.setColumns(20);
        jEditor.setRows(5);
        jEditor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPaneEditor.setViewportView(jEditor);

        jDivider.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jDivider.setResizeWeight(0.7);

        jScrollPaneMessages.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPaneMessages.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jMessages.setEditable(false);
        jMessages.setColumns(20);
        jMessages.setRows(5);
        jMessages.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPaneMessages.setViewportView(jMessages);

        jStatusBar.setPreferredSize(new java.awt.Dimension(1500, 25));

        jFilePath.setText("Nenhum arquivo selecionado");

        javax.swing.GroupLayout jStatusBarLayout = new javax.swing.GroupLayout(jStatusBar);
        jStatusBar.setLayout(jStatusBarLayout);
        jStatusBarLayout.setHorizontalGroup(
            jStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStatusBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jFilePath)
                .addContainerGap(1324, Short.MAX_VALUE))
        );
        jStatusBarLayout.setVerticalGroup(
            jStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFilePath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jMainLayout = new javax.swing.GroupLayout(jMain);
        jMain.setLayout(jMainLayout);
        jMainLayout.setHorizontalGroup(
            jMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneEditor)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDivider)
                .addContainerGap())
            .addComponent(jScrollPaneMessages)
            .addGroup(jMainLayout.createSequentialGroup()
                .addGroup(jMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jMainLayout.setVerticalGroup(
            jMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainLayout.createSequentialGroup()
                .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPaneEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDivider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPaneMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToolNewFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToolNewFileMouseClicked
        compileController.toolNewFile();
    }//GEN-LAST:event_jToolNewFileMouseClicked

    private void jToolOpenFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToolOpenFileMouseClicked
        compileController.toolOpenFile();
    }//GEN-LAST:event_jToolOpenFileMouseClicked

    private void jToolSaveFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToolSaveFileMouseClicked
        compileController.toolSaveFile();
    }//GEN-LAST:event_jToolSaveFileMouseClicked

    private void jToolCopyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToolCopyMouseClicked
        compileController.toolCopy();
    }//GEN-LAST:event_jToolCopyMouseClicked

    private void jToolPasteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToolPasteMouseClicked
        compileController.toolPast();
    }//GEN-LAST:event_jToolPasteMouseClicked

    private void jToolCutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToolCutMouseClicked
        compileController.toolCut();
    }//GEN-LAST:event_jToolCutMouseClicked

    private void jToolCompileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToolCompileMouseClicked
        compileController.toolCompile();
    }//GEN-LAST:event_jToolCompileMouseClicked

    private void jToolTeamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToolTeamMouseClicked
        compileController.toolTeam();
    }//GEN-LAST:event_jToolTeamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jDivider;
    private javax.swing.JTextArea jEditor;
    private javax.swing.JLabel jFilePath;
    private javax.swing.JLabel jImageMenu;
    private javax.swing.JLabel jImageMenu1;
    private javax.swing.JLabel jImageMenu10;
    private javax.swing.JLabel jImageMenu11;
    private javax.swing.JLabel jImageMenu12;
    private javax.swing.JLabel jImageMenu13;
    private javax.swing.JLabel jImageMenu14;
    private javax.swing.JLabel jImageMenu3;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelMenu1;
    private javax.swing.JLabel jLabelMenu10;
    private javax.swing.JLabel jLabelMenu11;
    private javax.swing.JLabel jLabelMenu12;
    private javax.swing.JLabel jLabelMenu13;
    private javax.swing.JLabel jLabelMenu14;
    private javax.swing.JLabel jLabelMenu3;
    private javax.swing.JPanel jMain;
    private javax.swing.JTextArea jMessages;
    private javax.swing.JScrollPane jScrollPaneEditor;
    private javax.swing.JScrollPane jScrollPaneMessages;
    private javax.swing.JPanel jStatusBar;
    private javax.swing.JToolBar jToolBar;
    private javax.swing.JPanel jToolCompile;
    private javax.swing.JPanel jToolCopy;
    private javax.swing.JPanel jToolCut;
    private javax.swing.JPanel jToolNewFile;
    private javax.swing.JPanel jToolOpenFile;
    private javax.swing.JPanel jToolPaste;
    private javax.swing.JPanel jToolSaveFile;
    private javax.swing.JPanel jToolTeam;
    // End of variables declaration//GEN-END:variables
}
